version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.9
    steps:
      - run: go get -u golang.org/x/lint/golint
      - checkout
      - run: go get -v -t -d ./...
      - run: golint ./...
      - run: go vet ./...
